# registration
spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: vM3kAPq0QWm393tNBVhJ
            client-secret: GctI5jK1DV
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - profile_image
            client-name: Naver
          google:
            client-id: 98682930391-tndmstl5sc61s6mjcl9pn99qg0urodqb.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

