spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: ture
        format_sql: true
        ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: local
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  data:
    web:
      pageable:
        default-page-size: 6
        max-page-size: 2000
        one-indexed-parameters: true
      sort:
        sort-parameter: id,DESC
  logging:
    level:
      org.hibernate.sql: debug
