spring:
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  session:
    timeout: 86400
    store-type: jdbc
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  data:
    web:
      pageable:
        default-page-size: 6
        max-page-size: 2000
        one-indexed-parameters: true
  logging:
    level:
      org:
        hibernate:
          SQL: debug
          type:
            descriptor:
              sql:
                BasicBinder: trace
  profile:
    active: local
