spring:
  jpa:
    open-in-view: false
    hibernate:
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  session:
    timeout: 86400
    store-type: jdbc
  thymeleaf:
    cache: false
  data:
    web:
      pageable:
        default-page-size: 6
        max-page-size: 2000
        one-indexed-parameters: true
  logging:
    level:
      org:
        hibernate:
          SQL: debug
          type:
            descriptor:
              sql:
                BasicBinder: trace
