### 회원가입

POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "name": "sg",
  "email": "unpadded7479@duck.com",
  "password": "1123"
}

### 로그인

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "unpadded7479@duck.com",
  "password": 1234,
  "remember": 1
}

### 비밀번호 변경

POST http://localhost:8080/admin/setting/account/edit/password
Content-Type: application/json

{
  "email": "unpadded7479@duck.com",
  "originPassword": "1234",
  "newPassword": "1123"
}



