### 회원가입

POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "name": "sg",
  "email": "unpadded7479@duck.com",
  "password": "1123"
}

### 로그인

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "unpadded7479@duck.com",
  "password": 1123,
  "remember": 1
}

### 로그아웃

POST http://localhost:8080/logout

### 메인 페이지

GET http://localhost:8080/

### 글 쓰기

GET http://localhost:8080/post/new
