# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      SEGMENT_DOWNLOAD_TIMEOUT_MINS: '5'
      S3_BUCKET_NAME: ddoddi-github-action-build
    steps:
    - uses: actions/checkout@v4
    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
    - name: Run chmod to make gradlew executable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build


      # build한 후 프로젝트를 압축한다.
    - name: Make zip file
      run: zip -r ./blog-deploy.zip .
      shell: bash

      # Access Key와 Secret Access Key를 통해 권한을 확인한다.
      # 아래 코드에 Access Key와 Secret Key를 직접 작성하지 않는다.
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}        # 등록한 Github Secret이 자동으로 불려온다.
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}        # 등록한 Github Secret이 자동으로 불려온다.
        aws-region: ap-northeast-2

      # 압축한 프로젝트를 S3로 전송한다.
    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./blog-deploy.zip s3://$S3_BUCKET_NAME/blog-deploy.zip

      # CodeDeploy에게 배포 명령을 내린다.
    - name: Code Deploy
      run: >
        aws deploy create-deployment --application-name myblog-webserver
        --deployment-config-name CodeDeployDefault.AllAtOnce
        --deployment-group-name myblog-webserver-group
        --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=blog-deploy.zip
